main:
    saved_dir: '/media/vincentwu-cmlab/5aae4c8c-ef9b-414c-acc3-814927dbe8b7/models/nuclei_self_seg_3cls_label_dice_resnet50_all_100_WOBG_deeplabX'
    loaded_path: '/media/vincentwu-cmlab/5aae4c8c-ef9b-414c-acc3-814927dbe8b7/models/nuclei_self_seg_3cls_label_dice_resnet50_all_100_WOBG_deeplabX/checkpoints/model_50.pth' # The loaded_path is necessary.

net:
    name: 'DeepLabV3Plus'
    kwargs:
        in_channels: 3
        out_channels: 3

losses:
    - name: 'DiceWOBGLoss'
      weight: 1.0

metrics:
    - name: 'F1Score'
    - name: 'AggreagteJaccardIndex'
    - name: 'EnsembleDice'

predictor:
    name: 'NucleiSelfSegPredictor'
    kwargs:
        data_dir: '/home/vincentwu-cmlab/cell_data/DSB2018plus'
        data_split_list: '/home/vincentwu-cmlab/template/data_split/DSB2018plus/All/train_val_test.json'
        label_type: '3cls_label' #choices: ['instance', '3cls_label', 'watershed_label']
        transforms:
            - name: 'Normalize'
              kwargs:
                  means: [0.485, 0.456, 0.406]
                  stds: [0.229, 0.224, 0.225]
            - name: 'ToTensor'
        sample_size: [256, 256]
        shift: [128, 128]
        post_process: 'watershed'
        device: 'cuda:0'
        saved_dir: '/media/vincentwu-cmlab/5aae4c8c-ef9b-414c-acc3-814927dbe8b7/models/nuclei_self_seg_3cls_label_dice_resnet50_all_100_WOBG_deeplab'
        exported: true
