main:
    random_seed: 0
    saved_dir: '/media/vincentwu-cmlab/5aae4c8c-ef9b-414c-acc3-814927dbe8b7/models/nuclei_self_seg_3cls_label_dice_resnet50_all_25'
    initial_model_path: '/media/vincentwu-cmlab/5aae4c8c-ef9b-414c-acc3-814927dbe8b7/models/nuclei_initial_seg_3cls_label_dice_resnet50_all_25/checkpoints/model_best.pth' 
    
dataset:
    name: 'NucleiSelfSegDataset'
    kwargs:
        data_dir: '/home/vincentwu-cmlab/cell_data/DSB2018plus'
        data_split_list: '/home/vincentwu-cmlab/template/data_split/DSB2018plus/All/train_val_test.json'
        label_type: '3cls_label'
        label_proportion: 0.25
        train_preprocessings:
            - name: 'Normalize'
              kwargs:
                  means: [0.485, 0.456, 0.406]
                  stds: [0.229, 0.224, 0.225]
            - name: 'RandomCrop'
              kwargs:
                  size: [256, 256]
        valid_preprocessings:
            - name: 'Normalize'
              kwargs:
                  means: [0.485, 0.456, 0.406]
                  stds: [0.229, 0.224, 0.225]
            - name: 'RandomCrop'
              kwargs:
                  size: [256, 256]
        augments:
            - name: 'RandomRotation'
              kwargs:
                  degrees: [-30.0, 30.0]
                  prob: 0.25
            - name: 'RandomHorizontalFlip'
              kwargs:
                  prob: 0.25
            - name: 'RandomVerticalFlip'
              kwargs:
                  prob: 0.25
        transforms:
            - name: 'ToTensor'

dataloader:
    name: 'Dataloader'
    kwargs:
        train_batch_size: 8
        valid_batch_size: 1
        shuffle: true
        num_workers: 8

label_generator:
    name: 'ResNet50UNet'
    kwargs:
        in_channels: 3
        out_channels: 3

net:
    name: 'ResNet50UNet'
    kwargs:
        in_channels: 3
        out_channels: 3

losses:
    - name: 'DiceWOBGLoss'
      weight: 1.0

metrics:
    - name: 'Dice'

optimizer:
    name: 'Adam'
    kwargs:
        lr: 0.0001
        weight_decay: 0
        amsgrad: false

#lr_scheduler:
#    name: 'StepLR'
#    kwargs:
#        step_size: 30
#        gamma: 0.1

logger:
    name: 'NucleiSelfSegLogger'
    kwargs:
        dummy_input: [16, 3, 256, 256]

monitor:
    name: 'Monitor'
    kwargs:
        mode: 'min'
        target: 'DiceWOBGLoss'
        saved_freq: 5
        early_stop: 0

trainer:
    name: 'NucleiSelfSegTrainer'
    kwargs:
        device: 'cuda:0'
        num_rounds: 5
        num_epochs_per_rounds: 10
