main:
    random_seed: 'unet2d'
    saved_dir: '/home/peter850706/template/models/kits_clf_seg/seg/unet2d/'

dataset:
    name: 'KitsClfSegDataset'
    kwargs:
        data_dir: "/home/peter850706/kits19_slice/data/"
        data_split_csv: "/home/peter850706/kits19_slice/dataset_split.csv"
        task: 'seg'
        train_transforms:
            - name: 'RandomCrop'
              kwargs:
                  size: [256, 256]
            - name: 'Normalize'
            - name: 'ToTensor'
        valid_transforms:
            - name: 'Normalize'
            - name: 'ToTensor'

dataloader:
    name: 'Dataloader'
    kwargs:
        train_batch_size: 16
        valid_batch_size: 1
        shuffle: true
        num_workers: 8

net:
    name: 'UNet'
    kwargs:
        in_channels: 1
        out_channels: 3

losses:
    - name: 'DiceLoss'
      weight: 1.0

metrics:
    - name: 'Dice'

optimizer:
    name: 'Adam'
    kwargs:
        lr: 0.001
        weight_decay: 0
        amsgrad: false

logger:
    name: 'KitsSegLogger'
    kwargs:
        dummy_input: [16, 1, 256, 256]

monitor:
    name: 'Monitor'
    kwargs:
        mode: 'max'
        target: 'Dice'
        saved_freq: 10
        early_stop: 0

trainer:
    name: 'KitsSegTrainer'
    kwargs:
        device: 'cuda:0'
        num_epochs: 100
