main:    
    random_seed: 'resnet34'
    saved_dir: '/tmp2/tungi893610/kits_result/clf/debug'

dataset:
    name: 'KitsClfSegDataset'
    kwargs:
        data_dir: '/tmp2/tungi893610/kits_preprocess_data/'
        data_split_csv: '/tmp2/tungi893610/dataset_split.csv'
        task: 'clf'
        #  crop_transforms:
        #  - name: 'RandomCrop'
        #  kwargs:
        #  size: [256, 256]
        #  - name: 'Normalize'
        #  - name: 'ToTensor'
        train_transforms:
            - name: 'RandomCrop'
              kwargs:
                size: [256, 256]
                #- name: 'RandomElasticDeformation'
                #kwargs:
                #prob: 0.8
            - name: 'Normalize'
            - name: 'ToTensor'
        valid_transforms:
            - name: 'Normalize'
            - name: 'ToTensor'

dataloader:
    name: 'Dataloader'
    kwargs:
        train_batch_size: 128
        valid_batch_size: 1
        shuffle: true
        num_workers: 8

net:
    name: 'ClfNet'
    kwargs:
        num_classes: 2
        name: 'resnet34'
        pretrained: false

losses:
        #- name: 'CrossEntropyLoss'
        #kwargs:
        #weight: [0.1, 0.9]
        #weight: 1.0
      
    - name: 'WeightedCrossEntropyLoss'
      kwargs:
        weight: [0.2, 0.8]
      weight: 1.0
      
       # - name: 'FocalLoss'
       # kwargs:
       #      alpha: [1.0, 1.0]
       #      gamma: 2
       #  weight: 1.0

metrics:
    - name: 'Accuracy'
    - name: 'F1score'
    - name: 'TPRate'
    - name: 'TNRate'
    - name: 'FNRate'
    - name: 'FPRate'

optimizer:
    name: 'Adam'
    kwargs:
        lr: 0.0001
        weight_decay: 0.00001
        amsgrad: false

logger:
    name: 'KitsClfLogger'
    kwargs:
        dummy_input: [32, 1, 256, 256]

monitor:
    name: 'Monitor'
    kwargs:
        mode: 'max'
        target: 'Accuracy'
        saved_freq: 10
        early_stop: 0

trainer:
    name: 'KitsClfTrainer'
    kwargs:
        device: 'cuda:0'
        num_epochs: 128

