main:
    saved_dir: '/home/vincentwu-cmlab/template/models/nuclei_initial_seg_3cls_label_dice_resnet50_all'
    loaded_path: '/home/vincentwu-cmlab/template/models/nuclei_initial_seg_3cls_label_dice_resnet50_all/checkpoints/model_best.pth' # The loaded_path is necessary.

dataset:
    name: 'NucleiInitialSegDataset'
    kwargs:
        data_dir: '/home/vincentwu-cmlab/cell_data/DSB2018plus'
        data_split_list: '/home/vincentwu-cmlab/template/data_split/DSB2018plus/All/train_val_test.json'
        label_type: '3cls_label' #choices: ['instance', '3cls_label', 'watershed_label']
        label_proportion: 0.5
        valid_transforms:
            - name: 'Normalize'
              kwargs:
                  means: [0.485, 0.456, 0.406]
                  stds: [0.229, 0.224, 0.225]
            - name: 'ToTensor'

dataloader:
    name: 'Dataloader'
    kwargs:
        batch_size: 1
        shuffle: false
        num_workers: 8

net:
    name: 'ResNet50UNet'
    kwargs:
        in_channels: 3
        out_channels: 3

losses:
    #- name: 'MyBinaryCrossEntropyLoss'
    #  weight: 0.5
    #- name: 'JaccardLoss'
    #  weight: 0.5
    - name: 'DiceLoss'
      weight: 1.0

metrics:
    - name: 'Dice'

predictor:
    name: 'NucleiInitialSegPredictor'
    kwargs:
        device: 'cuda:0'