main:
    saved_dir: '/home/vincentwu-cmlab/template/models/nuclei_initial_seg_watershed_label_resnet50_all'
    loaded_path: '/home/vincentwu-cmlab/template/models/nuclei_initial_seg_watershed_label_resnet50_all/checkpoints/model_best.pth' # The loaded_path is necessary.

dataset:
    name: 'NucleiInitialSegDataset'
    kwargs:
        data_dir: '/home/vincentwu-cmlab/cell_data/DSB2018plus'
        data_split_list: '/home/vincentwu-cmlab/template/data_split/DSB2018plus/All/train_val_test.json'
        label_type: 'watershed_label' #choices: ['instance', '3cls_label', 'watershed_label']
        label_proportion: 0.5
        transforms:
            - name: 'Normalize'
              kwargs:
                  means: [0.485, 0.456, 0.406]
                  stds: [0.229, 0.224, 0.225]
            - name: 'ToTensor'

dataloader:
    name: 'Dataloader'
    kwargs:
        batch_size: 1
        shuffle: false
        num_workers: 8

net:
    name: 'ResNet50UNet'
    kwargs:
        in_channels: 3
        out_channels: 4

losses:
    - name: 'AngleLoss'
      weight: 0.1
    - name: 'EnergyL2Loss'
      weight: 0.1
    - name: 'BinaryDiceLoss'
      weight: 0.8

metrics:
    - name: 'Dummy'

predictor:
    name: 'NucleiInitialSegPredictor'
    kwargs:
        device: 'cuda:0'
        saved_dir: '/home/vincentwu-cmlab/template/models/nuclei_initial_seg_watershed_label_resnet50_all'
        exported: true