main:
    random_seed: 0
    #saved_dir: '/home/vincentwu-cmlab/template/models/nuclei_initial_seg_3cls_label_dice/'
    saved_dir: '/home/vincentwu-cmlab/template/models/nuclei_initial_seg_watershed_label2/'
    #loaded_path: 'path/to/checkpoint.pth' # The loaded_path is not necessary.

dataset:
    name: 'NucleiInitialSegDataset'
    kwargs:
        data_dir: '/home/vincentwu-cmlab/cell_data/DSB2018plus/stage_1_train/'
        data_split_list: '/home/vincentwu-cmlab/template/data_split/DSB2018plus/stage_1_train/train_val_test.json'
        label_type: 'watershed_label' #choices: ['instance', '3cls_label', 'watershed_label']
        label_proportion: 0.5
        train_transforms: # Could define multiple transforms.
            - name: 'RandomCrop'
              kwargs:
                  size: [256,256]
            - name: 'Normalize'
              kwargs:
                  means: [0.485, 0.456, 0.406]
                  stds: [0.229, 0.224, 0.225]
            - name: 'ToTensor'
              #- name: 'HorFlip'
              #- name: 'VerFlip'
              #- name: 'Rotate'
        valid_transforms:
            - name: 'Normalize'
              kwargs:
                  means: [0.485, 0.456, 0.406]
                  stds: [0.229, 0.224, 0.225]
            - name: 'ToTensor'

dataloader:
    name: 'Dataloader'
    kwargs:
        train_batch_size: 16
        valid_batch_size: 1
        shuffle: true
        num_workers: 8

net:
    name: 'UNet'
    kwargs:
        in_channels: 3
        out_channels: 4

losses:
    #- name: 'MyBinaryCrossEntropyLoss'
    #  weight: 0.5
    #- name: 'JaccardLoss'
    #  weight: 0.5
    #- name: 'DiceLoss'
    #  weight: 1.0
    #- name: 'DisplacementFieldLoss'
    #  weight: 1.0
    - name: 'AngleLoss'
      weight: 0.08
    - name: 'EnergyL2Loss'
      weight: 0.02
    - name: 'BinaryDiceLoss'
      weight: 0.9

metrics:
    #- name: 'Dice'
    - name: 'Dummy'

optimizer:
    name: 'Adam'
    kwargs:
        lr: 0.001
        weight_decay: 0
        amsgrad: false

# The lr_scheduler section is not necessary.
lr_scheduler:
    name: 'StepLR'
    kwargs:
        step_size: 30
        gamma: 0.1

logger:
    name: 'NucleiInitialSegLogger'
    kwargs:
        dummy_input: [16, 3, 256, 256]

monitor:
    name: 'Monitor'
    kwargs:
        mode: 'min'
        target: 'BinaryDiceLoss'
        saved_freq: 10
        early_stop: 0

trainer:
    name: 'NucleiInitialSegTrainer'
    kwargs:
        device: 'cuda:0'
        num_epochs: 50
