main:
    random_seed: 0
    num_models: 2
    saved_dir: '/media/vincent/MyDisk/models/nuclei_co_seg_3cls_label_dice_resnet50_all_50'
    
dataset:
    name: 'NucleiCoSegDataset'
    kwargs:
        data_dir: '/tmp2/cell_data/DSB2018plus/stage_1_train'
        data_split_list: '/tmp2/template/data_split/DSB2018plus/stage_1_train/train_val_test.json'
        label_type: '3cls_label'
        label_proportion: 0.5
        train_preprocessings:
            - name: 'Normalize'
              kwargs:
                  means: [0.485, 0.456, 0.406]
                  stds: [0.229, 0.224, 0.225]
            - name: 'RandomCrop'
              kwargs:
                  size: [256, 256]
        valid_preprocessings:
            - name: 'Normalize'
              kwargs:
                  means: [0.485, 0.456, 0.406]
                  stds: [0.229, 0.224, 0.225]
            - name: 'RandomCrop'
              kwargs:
                  size: [256, 256]
        augments:
            - name: 'RandomRotation'
              kwargs:
                  degrees: [-30.0, 30.0]
                  prob: 0.25
            - name: 'RandomHorizontalFlip'
              kwargs:
                  prob: 0.25
            - name: 'RandomVerticalFlip'
              kwargs:
                  prob: 0.25
        transforms:
            - name: 'ToTensor'

dataloader:
    name: 'Dataloader'
    kwargs:
        train_batch_size: 8
        valid_batch_size: 1
        shuffle: true
        num_workers: 8    

segmentator:
    name: 'ResNet50UNet'
    kwargs:
        in_channels: 3
        out_channels: 3

sup_loss:
    name: 'DiceWOBGLoss'

jsd_loss:
    #name: 'JSD_2D'
    name: 'DummyLoss'

optimizer:
    name: 'Adam'
    kwargs:
        lr: 0.0001
        weight_decay: 0
        amsgrad: false

seg_scheduler:
    name: 'StepLR'
    kwargs:
        step_size: 30
        gamma: 0.1

cot_scheduler:
  name: RampScheduler
  kwargs:
    begin_epoch: 0
    max_epoch: 50
    max_value: 0.5
    ramp_mult: -5

adv_scheduler:
  name: RampScheduler
  kwargs:
    begin_epoch: 20
    max_epoch: 50
    max_value: 0.05
    ramp_mult: -5

adv_training:
  eplision:  0.03

logger:
    name: 'NucleiCoSegLogger'
    kwargs:
        dummy_input: [16, 3, 256, 256]

monitor:
    name: 'CoMonitor'
    kwargs:
        mode: 'min'
        target: 'Loss'
        saved_freq: 5
        early_stop: 0

trainer:
    name: 'NucleiCoSegTrainer'
    kwargs:
        device: 'cuda:0'
        num_epochs: 100